final List<String> BobilEquipment = [
  'Letmetallfelger',
  'Støtteben',
  'Hengerfeste',
  'Takgrind/Stige',
  'Gassalarm',
  'Airbag fører',
  'Antiskrens',
  'Dieselpartikkelfilter',
  'Luftfjæring',
  'Klimaanlegg bodel',
  'Luftvarme',
  'Vannbåren varme',
  'Frostfri spillvannstank',
  'Myggdør',
  'Kjøleskap',
  'Stekeovn',
  'Elektriske vinduer',
  'Lose tepper',
  'Cruisekontroll',
  'Kjørecomputer',
  'Radio/CD',
  'Manuell parabol',
  'Automatisk parabol',
  'Vinterhjul',
  'Markise',
  'Sykkelstativ',
  'ABS-bremser',
  'Bilalarm',
  'Airbag passasjer',
  'Antispinn',
  'Sentrallås',
  'Klimaanlegg bildel',
  'Elvarme',
  'Gulvvarme',
  'Tilleggsvarme',
  'Fast toalett',
  'Gassuttak',
  'Mikrobølgeovn',
  'Elektriske speil',
  'Skinninteriør',
  'Røykfri',
  'Ryggekamera',
  'Navigasjonssystem',
  'TV-antenne',
  'TV',
  'DVD',
];

final List<String> bobilBrands = [
  "Adria", "Ahorn", "Airstream", "Atlas", "Autostar", "Basoglu", "Bavaria", "Bela", "Benimar", "Bjølseth", "Bravia", "Bürstner", "CI", "CS", "Cabby", "Camp_Let", "Carado", "Caravelair", "Carbon Tear", "Carthago", "Cavalier", "Challenger", "Chausson", "Chevrolet", "Clever", "Combi-Camp", "Concorde", "Crawler", "DAF", "Decamp", "Dethleffs", "Derubis", "Dream", "Dreamer", "Eifelland", "Elnagh", "Esterel", "Eura Mobil", "FR-Mobil", "Fiat awning", "Fendt", "Fiat", "Flair", "Fleetwood", "Fleurette", "Ford", "Frankia", "GG", "Giant", "Giottiline", "Globe-Traveller", "Globecar", "Glucksmobile", "Grey", "Gulfstream", "Hero Camper", "Hino", "Hobby", "Holiday Rambler", "Home car", "Caravans", "Humming", "Illusion", "Itineo", "CABLE", "Karmann", "Kentucky Camp", "Kip", "Knaus", "Kulba", "LMC", "LMC/Münsterland", "La Strada", "Laika", "Le Voyageur", "Lifestyle Camper", "Malibu", "Mclouis", "Very Mobile", "Mercedes-Benz", "Miller", "Mink", "Mirage", "Mobile Traveller", "Mobile vet", "Monaco", "Morelo", "Mouflon", "Neo Traveller", "Niesmann-Bischoff", "Nissan", "Nordic", "The Norwegian hanger", "Orange camp", "P.L.A", "Peugeot", "Phoenix", "Pilot", "Polar", "Poletta", "Sausage", "RMB", "Raidhoo Campers", "Rapido", "Resp", "Rimor", "Riviera", "Roadcar", "Rockwood", "Roles Team", "Savsjø", "Scania", "Sharky", "SMV", "Solifer", "Sprite", "Sterckeman", "Sun Living", "Sunlight", "Swift", "T.E. Caravan", "Tabbert", "Tec", "Tourne", "Triple E", "Troll", "VANTourer", "Volkswagen", "WINGAMM", "Weinsberg", "Weippert", "Westfalia", "Wilk", "Willerby", "Winnebago", "Other"
];
